# Generated by Django 4.0.3 on 2022-03-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlenames',
            old_name='product_name',
            new_name='name',
        ),
    ]
